version: '3.8'
services:
   db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - data:/var/lib/mysql
      ports:
        - 33077:3306

   phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - "8077:80"
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      depends_on:
         - db
      volumes:
        - phpmyadmin:/sessions

volumes:
  data:
  phpmyadmin:
